### ISSUE TITLE
Remove orphaned sections and tasks when deleting a project

### ISSUE THREAD

**Issue by NickLewanowicz** [Kickit/kickit-backend#12]
Currently when deleting a project all sections and tasks become orphaned and cant be accessed. 

We should clean these up prior to deleting the project. To do this we will just need to get the sections that point to a project, and the tasks that point to each section and loop through them to delete.

**Comment by ermel272** [comment]
Note: I'll start working on a bug fix for this once https://github.com/Kickit/kickit-backend/pull/16 gets merged
